# -*- coding: utf-8 -*-
"""CL-AI practical - 9

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Z0Xp917tnWQnB74ydFUdx1QtrpjVX91T
"""

import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.preprocessing import StandardScaler

from sklearn.neural_network import MLPClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score

#loading the CSV
data = pd.read_csv("IRIS.csv")

# Separate features and target
X = data.drop('species', axis=1)
y = data['species']

# Train-Test Split

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

# Feature Scaling (models that need it)

scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

from sklearn.neural_network import MLPClassifier
from sklearn.model_selection import GridSearchCV
# The following imports and code are included to ensure X_train_scaled and y_train are defined.
# They should have been defined in previous cells, but are re-added here to resolve the NameError.
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

# Train-Test Split
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

# Feature Scaling (models that need it)
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

# 1. MLP Classifier (Grid Search Tuned)

mlp = MLPClassifier(max_iter=500, random_state=42)
mlp_param_grid = {
    'hidden_layer_sizes': [(32,), (32,16), (64,32)],
    'activation': ['relu', 'tanh'],
    'solver': ['adam'],
    'alpha': [0.0001, 0.01]
}

mlp_grid = GridSearchCV(
    mlp,
    mlp_param_grid,
    cv=5,
    scoring='accuracy',
    n_jobs=-1
)
mlp_grid.fit(X_train_scaled, y_train)
mlp_best = mlp_grid.best_estimator_
mlp_pred = mlp_best.predict(X_test_scaled)

# 2. Logistic Regression

log_reg = LogisticRegression(max_iter=1000)
log_reg.fit(X_train_scaled, y_train)
log_pred = log_reg.predict(X_test_scaled)

# 3. Support Vector Machine (SVM)

svm = SVC(kernel='rbf', probability=True)
svm.fit(X_train_scaled, y_train)
svm_pred = svm.predict(X_test_scaled)

# 4. Random Forest (No Scaling Required)

rf = RandomForestClassifier(
    n_estimators=100,
    random_state=42
)
rf.fit(X_train, y_train)
rf_pred = rf.predict(X_test)

# Performance Comparison

results = pd.DataFrame({
    "Model": [
        "MLP (Tuned)",
        "Logistic Regression",
        "SVM",
        "Random Forest"
    ],
    "Accuracy": [
        accuracy_score(y_test, mlp_pred),
        accuracy_score(y_test, log_pred),
        accuracy_score(y_test, svm_pred),
        accuracy_score(y_test, rf_pred)
    ],
    "Precision": [
        precision_score(y_test, mlp_pred, average='weighted'),
        precision_score(y_test, log_pred, average='weighted'),
        precision_score(y_test, svm_pred, average='weighted'),
        precision_score(y_test, rf_pred, average='weighted')
    ],
    "Recall": [
        recall_score(y_test, mlp_pred, average='weighted'),
        recall_score(y_test, log_pred, average='weighted'),
        recall_score(y_test, svm_pred, average='weighted'),
        recall_score(y_test, rf_pred, average='weighted')
    ],
    "F1-score": [
        f1_score(y_test, mlp_pred, average='weighted'),
        f1_score(y_test, log_pred, average='weighted'),
        f1_score(y_test, svm_pred, average='weighted'),
        f1_score(y_test, rf_pred, average='weighted')
    ]
})

print("Best MLP Hyperparameters:")
print(mlp_grid.best_params_)
print("\nModel Comparison Results:")
print(results)

